Repository DEAD10C5/ctf-cloud-tools, pull requests merged in 2023-07, with the labels that each got.

#12 fix the doas config
  bin/install_peirates.sh
  docker/.dockerignore
  docker/Dockerfile
  docs/notes.txt
Labels: bug, cloudbot-testing

#17 Update YOU-SAID-THIS-WAS-A-TEST
  .reuse/dep5
  bin/install_cloudjack.sh
  bin/install_peirates.sh
  bin/install_scoutsuite.sh
  images/poem.png
  test/YOU-SAID-THIS-WAS-A-TEST
Labels: enhancement, 🌮 tacos 🌮, cloudbot-testing

#18 work on installer scripts
  bin/install_aws.sh
  bin/install_azure.sh
  bin/install_cloudfox.sh
  bin/install_cloudjack.sh
  bin/install_gcloud.sh
  bin/install_gitoops.sh
  bin/install_s3scanner.sh
  bin/install_scoutsuite.sh
  bin/setup.sh
  docs/cloudjack.md
  docs/gitoops.md
  docs/scoutsuite.md
Labels: cloudbot-testing

#22 test trivy
  .github/workflows/trivy.yaml
Labels: cloudbot-testing

#24 test devcontainer
  .devcontainer/devcontainer.json
  .dockerignore
  .profile
  .reuse/dep5
  bin/bats_setup.sh
  bin/install_cloudfox.sh
  bin/install_cloudsplaining.sh
  bin/setup.sh
  tests/test.bats
Labels: cloudbot-testing
